--- 
- 
  hosts: 34.239.126.166 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/go-app.pem
  ignore_errors: yes
  become: true
  become_user: root 
  tasks: 
    - 
      args: 
        chdir: /root/go/
      command: "sudo rm -rf /root/go/goapp-ansible-master/"
      name: "Clean artifact path"
    - 
      git: 
        dest: /root/go/goapp-ansible-master
        repo: "https://github.com/vjananth89/goapp-ansible-master.git"
    - 
      args: 
        chdir: /root/go/goapp-ansible-master/
      command: "sudo go get github.com/gorilla/mux"
      name: "Download gorilla package"
    - 
      args: 
        chdir: /root/go/goapp-ansible-master/
      command: "sudo go get github.com/lib/pq"
      name: "Download postgres packages"
    - 
      args: 
        chdir: /root/go/goapp-ansible-master/src/github.com/vpandian/goapp-postgres-master/
      command: "sudo go run main.go personHandler.go store.go &"
      register: command_result
      failed_when: "path not found"
      name: "Start the app"
